Adds supports for unicode-encoded names when creating an avatar from a name's initial
nextcloud/nextcloud-vue pull request #1407
Opened 2020-09-16 13:16 UTC by StCyr

Fix to https://github.com/nextcloud/nextcloud-vue/issues/1406

not tested though :-)

Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

2020-10-12 16:45 UTC, skjnldsv approved these changes

2020-10-13 09:10 UTC, ChristophWurst approved these changes

2020-10-13 09:12 UTC, ChristophWurst requested changes
![Bildschirmfoto von 2020-10-13 11-12-38](https://user-images.githubusercontent.com/1374172/95840905-0869fb80-0d45-11eb-9552-4515e9015f18.png)

Does not seem to work as expected?

2020-10-13 09:16 UTC, ChristophWurst commented
Use this 
![Bildschirmfoto von 2020-10-13 11-15-43](https://user-images.githubusercontent.com/1374172/95841283-79111800-0d45-11eb-8f82-e1b334d085ac.png)

Ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

2020-10-13 09:49 UTC, StCyr commented
> Use this
> ![Bildschirmfoto von 2020-10-13 11-15-43](https://user-images.githubusercontent.com/1374172/95841283-79111800-0d45-11eb-8f82-e1b334d085ac.png)
> 
> Ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt
> 
> And it also work with simple names
> 
> ![Bildschirmfoto von 2020-10-13 11-16-29](https://user-images.githubusercontent.com/1374172/95841377-9645e680-0d45-11eb-961e-22588dbaa591.png)

Thanks! I'll update my PR (sorry for the wrong solution I've proposed)

2020-10-13 09:51 UTC, skjnldsv commented
Btw shouldn't we use the double initials for the displayname?

2020-10-13 09:57 UTC, StCyr commented
> Btw shouldn't we use the double initials for the displayname?

I also wonder.

I think it was the case earlier, and then, at some point in time, NC has started to display only 1 initial...

2020-10-13 10:01 UTC, skjnldsv commented
> I think it was the case earlier, and then, at some point in time, NC has started to display only 1 initial...

It's the opposite, we showed only one, but now show two :wink: 
https://github.com/nextcloud/server/pull/18745

2020-10-13 10:13 UTC, StCyr commented
> > I think it was the case earlier, and then, at some point in time, NC has started to display only 1 initial...
> 
> It's the opposite, we showed only one, but now show two 😉
> [nextcloud/server#18745](https://github.com/nextcloud/server/pull/18745)
> https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/lib/private/Avatar/Avatar.php#L98-L100

Ha! nice 👍 

I can push this change here if you want, that would be great I think

2020-10-13 10:15 UTC, skjnldsv commented
> I can push this change here if you want, that would be great I think

Sure, it feels relevant enough! :+1:

2020-10-13 11:06 UTC, skjnldsv commented on src/components/Avatar/Avatar.vue
> +				const userId = this.getUserIdentifier
please use something else than `userId`, this is also the displayName :)

2020-10-13 12:53 UTC, skjnldsv approved these changes

2020-10-13 15:07 UTC, ChristophWurst approved these changes

2020-10-13 15:07 UTC, merged