Quickfix for action button and material design icon
nextcloud/nextcloud-vue pull request #1614
Opened 2020-11-27 17:15 UTC by PVince81

When using a material design icon in the icon slot, this fix will
properly align it vertically.

- [ ] add example in docs if possible

2020-11-27 17:28 UTC, PVince81 commented
Without the CSS fix:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/277525/100473319-5c0a8b80-30de-11eb-8bf5-b816d9e74e9d.png">

With the CSS fix:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/277525/100473292-4ac17f00-30de-11eb-9889-10462de39d2b.png">

2020-11-30 07:32 UTC, ChristophWurst approved these changes

2020-11-30 13:30 UTC, ma12-co requested changes
See comments

2020-11-30 13:30 UTC, ma12-co commented on src/components/ActionButton/ActionButton.vue
> +				:size="24"
```suggestion
				:size="16"
```

2020-11-30 13:30 UTC, ma12-co commented on src/components/ActionButton/ActionButton.vue
> +				:size="24"
```suggestion
				:size="16"
```

2020-11-30 13:30 UTC, ma12-co commented on src/components/ActionButton/ActionButton.vue
> +				fill-color="#000000"
```suggestion
```

2020-11-30 13:30 UTC, ma12-co commented on src/components/ActionButton/ActionButton.vue
> +				fill-color="#000000"
```suggestion
```

2020-11-30 15:02 UTC, PVince81 commented
@ma12-co seems 16 is too small

here I used 16 for the material design icons:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/277525/100625659-18559300-3325-11eb-9415-9b81e0ff9cdc.png">

hmmm, but 24 is maybe too big indeed:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/277525/100625784-3de29c80-3325-11eb-90ef-47588e389d7b.png">

here's 20:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/277525/100625858-5e125b80-3325-11eb-9625-9a203048b63e.png">

let's go with 20 then ?

this is anyway just a code example... ideally in the future we should have a way to only provide the icon name...

2020-12-01 09:01 UTC, ma12-co commented
@PVince81 I agree that 18 or 20 would look better, but for now 16px is our default in Nextcloud. We can talk about bumping that up a bit but I wouldn't do it here.

2020-12-01 10:01 UTC, PVince81 commented
> @PVince81 I agree that 18 or 20 would look better, but for now 16px is our default in Nextcloud. We can talk about bumping that up a bit but I wouldn't do it here.

ok, fine. adjusted. please review

2020-12-01 10:38 UTC, PVince81 commented
rebased for cypress fix

2020-12-01 12:24 UTC, ChristophWurst approved these changes

2020-12-01 13:28 UTC, juliushaertl approved these changes

2020-12-01 14:47 UTC, merged