Improve multiselect tag
nextcloud/nextcloud-vue pull request #1718
Opened 2021-02-19 11:13 UTC by GretaD

Signed-off-by: GretaD <gretadoci@gmail.com>
![Kazam-screencast-00013](https://user-images.githubusercontent.com/12728974/108497506-d563e580-72ab-11eb-9777-78348e1d1c80.gif)

2021-02-19 11:19 UTC, GretaD commented
@skjnldsv I did what you suggested(btw we do need the limit) and the final result is this one. On mail i added :limit="4", but it doesnt apply, see [here](https://github.com/nextcloud/mail/pull/4401/files#diff-77b33550ce11bdb5cd04cb76105da60c54610d3c204ab3c20f513e2336a66d51R32).

it still only shows one. Any idea whats blocking it? I tried width and such but didnt work.

2021-03-01 15:16 UTC, skjnldsv requested changes
![Capture d’écran_2021-03-01_16-16-12](https://user-images.githubusercontent.com/14975046/109517363-75d6b880-7aa9-11eb-991d-fbf99fa3be74.png)
This seems to conflict with the normal layout :thinking:

2021-03-03 10:51 UTC, GretaD commented
@skjnldsv my last fixup will do smth like this, without breaking(if i tested it right) the other multiselect options. The only thing i cannot fix is, moving the input below and not having it inline, like in this fixup. 

![Kazam-screencast-00012](https://user-images.githubusercontent.com/12728974/109794231-f1557880-7c15-11eb-9659-8064ffb0dbd5.gif)

2021-03-08 09:53 UTC, skjnldsv commented on src/components/Multiselect/index.scss
> -				max-width: -moz-fit-content;
Why was this removed?

2021-03-08 10:06 UTC, skjnldsv approved these changes
Other than the comment, it looks good on the docs and code

2021-03-09 08:45 UTC, ChristophWurst approved these changes
changes look fine

2021-03-09 09:39 UTC, merged