Create ActionCaption component
nextcloud/nextcloud-vue pull request #1739
Opened 2021-03-03 15:57 UTC by ma12-co

![Screenshot from 2021-03-03 15-52-30](https://user-images.githubusercontent.com/26852655/109833340-190a0800-7c39-11eb-87a2-cb64864859b6.png)

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

2021-03-03 16:09 UTC, nickvergessen reviewed
I think the color is too much inside an action component. Its okay in the navigation component but not in the action popover menu

2021-03-03 16:09 UTC, nickvergessen commented on src/components/ActionCaption/ActionCaption.vue
> +		color: var(--color-primary);
White on white incoming... Needs to use color-primary-element?

2021-03-03 16:33 UTC, ma12-co commented
> I think the color is too much inside an action component. Its okay in the navigation component but not in the action popover menu

Imo it creates a nice separation between actions and caption, but I don't have a strong opinion here. @jancborchardt  your call

2021-03-16 14:32 UTC, skjnldsv requested changes
Waiting fro @jancborchardt's return

2021-04-13 16:55 UTC, jancborchardt commented
> > I think the color is too much inside an action component. Its okay in the navigation component but not in the action popover menu
> 
> Imo it creates a nice separation between actions and caption, but I don't have a strong opinion here. @jancborchardt your call

I would agree the color _and_ boldness is too much for just a caption – since the options themselves are the important thing. I would actually set the caption in `var(--color-text-maxcontrast)` (and possibly not bold) and use the color (and maybe the boldness, but probably not) for the selected option instead.

2021-04-16 08:21 UTC, ma12-co commented
Allright, ready to review again

![Screenshot from 2021-04-16 09-19-54](https://user-images.githubusercontent.com/26852655/114994793-0ff59300-9e95-11eb-9f37-3047f3b411d8.png)

2021-04-16 08:32 UTC, skjnldsv approved these changes
Let's use variables :rocket:

2021-04-16 13:07 UTC, skjnldsv approved these changes

2021-04-16 14:06 UTC, PVince81 approved these changes
:+1:

2021-04-16 14:06 UTC, PVince81 commented
ohhh, a conflict!

2021-04-16 14:17 UTC, merged