Allow last crumb to shrink if all crumbs collapsed
nextcloud/nextcloud-vue pull request #1771
Opened 2021-03-20 14:31 UTC by raimund-schluessler

This PR allow the last breadcrumb in the breadcrumbs bar to shrink, in case all other breadcrumbs are already hidden. This prevents the breadcrumb from overflowing on narrow screens (e.g. iPhone 8).

Before:
![Screenshot_2021-03-20 Inventar - Nextcloud](https://user-images.githubusercontent.com/2496460/111873547-0a3d8800-8991-11eb-9abc-6cd05e48fb07.png)

![before](https://user-images.githubusercontent.com/2496460/111873557-175a7700-8991-11eb-938a-0b55340c35be.gif)

After:
![Screenshot_2021-03-20 Inventar - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/111873556-1295c300-8991-11eb-8ebf-757d36997326.png)

![after](https://user-images.githubusercontent.com/2496460/111873562-1f1a1b80-8991-11eb-8895-76bce1a5ae43.gif)

2021-03-22 12:12 UTC, skjnldsv commented on src/components/Breadcrumbs/Breadcrumbs.vue
> +	}
Please use BEM syntax
```suggestion
	&.crumb--collapsed  .crumb:last-child {
		min-width: 100px;
		flex-shrink: 1;
	}
```

2021-03-22 12:13 UTC, skjnldsv requested changes
See comments :)

2021-03-22 12:53 UTC, raimund-schluessler commented
> 
> 
> See comments :)

Done.

2021-03-22 12:54 UTC, skjnldsv approved these changes

2021-03-22 18:12 UTC, ChristophWurst approved these changes
ah yes, css

2021-03-22 18:12 UTC, merged

2025-05-02 07:07 UTC, skjnldsv commented on src/components/Breadcrumbs/Breadcrumbs.vue
> +		min-width: 100px;
Hey @raimund-schluessler , old PR, but is this really intended?
![image](https://github.com/user-attachments/assets/6330150a-714b-490d-8d1d-c8b6e0f3bdba)

2025-05-02 07:14 UTC, raimund-schluessler commented on src/components/Breadcrumbs/Breadcrumbs.vue
> +		min-width: 100px;
Well, I put it to prevent the last crumb to shrink to zero. But in your example, it's clearly not ideal.

2025-05-02 13:42 UTC, skjnldsv commented on src/components/Breadcrumbs/Breadcrumbs.vue
> +		min-width: 100px;
Ah, I'll see later if css magic allows that now that we are 4 years later :p