Use ActionButton for AppNavigationToggle
nextcloud/nextcloud-vue pull request #1844
Opened 2021-04-13 18:59 UTC by raimund-schluessler

This is another approach to https://github.com/nextcloud/nextcloud-vue/pull/1843. We simply use `ActionButton` for the `AppNavigationToggle` now and let it do the heavy lifting.

Toggle on hover:
![Screenshot_2021-04-13 Tasks - Nextcloud(2)](https://user-images.githubusercontent.com/2496460/114606052-13252f00-9c9b-11eb-9d67-bac650a89e4a.png)

2021-04-14 11:31 UTC, ma12-co approved these changes

2021-04-15 05:42 UTC, skjnldsv commented on src/components/AppNavigationToggle/AppNavigationToggle.vue
> +			@click="$emit('update:open', !open)">
really don't like actions inside templates, please put back into a method

2021-04-15 05:43 UTC, skjnldsv requested changes

2021-04-15 05:43 UTC, skjnldsv commented on src/components/AppNavigationToggle/AppNavigationToggle.vue
> +			@click="$emit('update:open', !open)">
really don't like actions inside templates, please put back into a method

2021-04-15 07:35 UTC, raimund-schluessler commented on src/components/AppNavigationToggle/AppNavigationToggle.vue
> +			@click="$emit('update:open', !open)">
Done.

2021-04-15 17:03 UTC, jancborchardt requested changes
When testing with a screenreader, the aria label seems to be duplicated, it reads:
> navigation, open navigation collapsed pushbutton, open navigation

And when the navigation is open:
> navigation, close navigation expanded pushbutton, close navigation

So it seems we should actually _not_ have the aria-label because the "navigation" already comes from the `role="navigation"` on the parent. Then it would just be "navigation, expanded pushbutton".

2021-04-15 17:10 UTC, raimund-schluessler commented
> 
> 
> When testing with a screenreader, the aria label seems to be duplicated, it reads:
> 
> > navigation, open navigation collapsed pushbutton, open navigation
> 
> And when the navigation is open:
> 
> > navigation, close navigation expanded pushbutton, close navigation
> 
> So it seems we should actually _not_ have the aria-label because the "navigation" already comes from the `role="navigation"` on the parent. Then it would just be "navigation, expanded pushbutton".

@jancborchardt Would it be possible that you adjust that? I don't have a screenreader at hand.

2021-04-15 18:26 UTC, jancborchardt commented
> @jancborchardt Would it be possible that you adjust that? I don't have a screenreader at hand.

I could try – but which system are you on? If you use GNOME, you can simply go to "Universal Access" and activate the screenreader from there. :)

2021-04-15 19:50 UTC, jancborchardt commented
Fixed it :) @raimund-schluessler the issue was simply that the `aria-label` was duplicating the text which was already in the ActionButton, so removing the `aria-label` fixed it.

2021-04-15 19:50 UTC, jancborchardt approved these changes
Works great now! :)

2021-04-15 19:53 UTC, jancborchardt commented
@skjnldsv could you check and approve if your change request is addressed? :)

2021-04-16 10:11 UTC, skjnldsv approved these changes

2021-04-16 10:18 UTC, merged

2021-04-22 11:26 UTC, jotoeri commented
How about a backport here? 😉