Fix ActionCaption layout
nextcloud/nextcloud-vue pull request #2043
Opened 2021-06-17 16:10 UTC by marcoambrosini

| Before | After |   
|--------|-------|
|   ![before](https://user-images.githubusercontent.com/26852655/122434239-d45b7000-cf8e-11eb-9ce8-5bf558686297.PNG)  |  ![after](https://user-images.githubusercontent.com/26852655/122434262-da515100-cf8e-11eb-9899-3dd05ff97350.PNG) |

2021-06-17 16:17 UTC, skjnldsv requested changes

2021-06-17 16:17 UTC, skjnldsv commented on src/components/ActionCaption/ActionCaption.vue
> +		height: 44px;
clickable area

2021-06-18 10:59 UTC, skjnldsv requested changes

2021-06-18 10:59 UTC, skjnldsv commented on src/components/ActionCaption/ActionCaption.vue
> +		height: var(--clickable-area);
```suggestion
		height: $clickable-area;
```

Same for the `line-height` line 56 btw

2021-06-22 16:22 UTC, juliushaertl approved these changes

2021-06-28 08:31 UTC, marcoambrosini commented
Need a review here :)

2021-06-28 09:35 UTC, skjnldsv approved these changes

2021-06-28 10:21 UTC, merged