Add aria-description to AppNavigationItem
nextcloud/nextcloud-vue pull request #2548
Opened 2022-03-14 12:32 UTC by JuliaKirschenheuter

required for https://github.com/nextcloud/calendar/issues/3955
used for https://github.com/nextcloud/calendar/pull/4045

Documentation for "aria-description": https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description

2022-03-15 18:09 UTC, skjnldsv approved these changes

2022-03-15 18:11 UTC, skjnldsv requested changes

2022-03-15 18:11 UTC, skjnldsv commented on src/components/AppNavigationItem/AppNavigationItem.vue
> +			default: '',
Should be null by default :)
![image](https://user-images.githubusercontent.com/14975046/158443998-f8737529-4afe-4a48-a78f-505235e40ea7.png)

2022-03-21 14:13 UTC, ChristophWurst approved these changes

2022-03-21 14:14 UTC, merged