Fix ListItem
nextcloud/nextcloud-vue pull request #2856
Opened 2022-07-18 21:25 UTC by jotoeri

This fixes two things:
- The ListItem was not really usable without subtitle but with counter. This now brings that case onto one line and fixes the ListItem height, so it looks properly.
- It introduces a compact-mode for the list item. Once used without subtitle or in a mixed case, the default sizes are quite large, esp. if compared to the old AppNavigationItem. Thus the compact mode reduces the size of the ListItem a bit, so the mixed case looks good.

Total result on forms:
![grafik](https://user-images.githubusercontent.com/47433654/179620090-937c0d67-dd41-4a5e-a03f-c2bb95c4bf87.png)

- [ ] Still to check, if breaking on other apps
- [ ] Compare to old PR on forms

2022-07-20 07:58 UTC, raimund-schluessler commented
@jotoeri Could you please show before and after pictures and describe a bit more what was/is the problem you are fixing here? If we change the padding of `ListItem` and of the `Actions` inside, we might break the alignment with other components in the library, so there should b good reasoning, as we likely need to change it for other components as well then.

2022-07-22 17:49 UTC, jotoeri commented
> @jotoeri Could you please show before and after pictures and describe a bit more what was/is the problem you are fixing here? If we change the padding of `ListItem` and of the `Actions` inside, we might break the alignment with other components in the library, so there should b good reasoning, as we likely need to change it for other components as well then.

Well, that's why it has the developing label and i had to check if this is, what i wanted. :wink: 
- You're right, the padding of the list-item is not necessary anymore. Compared to my initial base on the last release, the padding of the appnavigation already increased, so the padding here would be doubled.
- For the actions margin-left i have a specific before/after here. It just increases the space a little bit, if the text overflow gets hidden:

| Before | After |
|---|---|
| ![actions_old](https://user-images.githubusercontent.com/47433654/180494660-c5a82e8a-45b4-4e3d-bea3-e8963b5c4e1d.png) | ![actions_new2](https://user-images.githubusercontent.com/47433654/180495350-bf24f27b-0204-4791-8a37-a465a1a558a2.png) |
- For the whole PR i'll update the initial comment later :slightly_smiling_face:

2022-07-23 09:12 UTC, jotoeri commented
As i still need to double-check these changes with other apps, @raimund-schluessler do you know some apps that use the listItem?

2022-07-23 09:16 UTC, Chartman123 commented
@jotoeri A quick search within the Nextcloud organisation here on GitHub only brought up the mail app:

https://github.com/search?q=org%3Anextcloud+%22import+ListItem%22&type=code

But there might be of course other apps that are not connected to the organisation here.

2022-07-28 18:16 UTC, jotoeri commented
Just checked it on Talk and didn't see any problems. So should be good to go now. :slightly_smiling_face:

2022-07-28 18:25 UTC, jotoeri commented on src/components/ListItem/ListItem.vue
> +			margin-left: 4px;
| Before | After |
|---|---|
| ![actions_old](https://user-images.githubusercontent.com/47433654/180494660-c5a82e8a-45b4-4e3d-bea3-e8963b5c4e1d.png) | ![actions_new2](https://user-images.githubusercontent.com/47433654/180495350-bf24f27b-0204-4791-8a37-a465a1a558a2.png) |

2022-07-28 18:25 UTC, jotoeri commented on src/components/ListItem/ListItem.vue
> -		padding-right: 4px;
Shifted to counter margin, so it also applies if no subtitle used.

2022-07-29 05:40 UTC, marcoambrosini approved these changes

2022-07-29 05:48 UTC, Chartman123 approved these changes

2022-07-29 08:33 UTC, nimishavijay approved these changes

2022-07-29 09:01 UTC, marcoambrosini requested changes
@jotoeri could you add a compact example in the docs too?

2022-07-29 10:00 UTC, jotoeri commented
:+1: @marcoambrosini Can i easily get that to half width? Just add a style to the surrounding `ul`? :thinking:
![preview](https://user-images.githubusercontent.com/47433654/181735250-fa85f538-67c2-4aee-853e-8277dab6c4a3.png)

2022-07-29 11:34 UTC, marcoambrosini commented
@jotoeri sure thingy :)

2022-07-29 11:43 UTC, jotoeri commented
![preview](https://user-images.githubusercontent.com/47433654/181751780-b898c937-530f-4bc4-830c-08e68c305246.png)

2022-07-29 12:49 UTC, marcoambrosini approved these changes

2022-07-29 12:49 UTC, merged

2022-08-02 21:09 UTC, jotoeri commented
/backport to stable5