AppDetailsToggle uses Button, MD icon, directive
nextcloud/nextcloud-vue pull request #2887
Opened 2022-07-25 19:22 UTC by raimund-schluessler

This PR migrates the `AppDetailsToggle` to use a vue button and a material design icon, and explicitly imports the `tooltip` directive which at the moment needs to be imported by the app dev via `Vue.use()` which is error prone.

2022-07-26 07:43 UTC, nickvergessen requested changes

2022-07-26 07:43 UTC, nickvergessen commented on src/components/AppContent/AppDetailsToggle.vue
> +			<Arrowright :size="20" />
```suggestion
			<ArrowRight :size="20" />
```

and missing the import

2022-07-26 07:43 UTC, nickvergessen commented on src/components/AppContent/AppDetailsToggle.vue
> +import Tooltip from '../../directives/Tooltip/index.js'
```suggestion
import Tooltip from '../../directives/Tooltip/index.js'
import ArrowRight from 'vue-material-design-icons/ArrowRight'
```

2022-07-26 07:43 UTC, nickvergessen commented on src/components/AppContent/AppDetailsToggle.vue
> +		Button,
```suggestion
		Button,
		ArrowRight,
```

2022-07-26 07:57 UTC, raimund-schluessler commented on src/components/AppContent/AppDetailsToggle.vue
> +import Tooltip from '../../directives/Tooltip/index.js'
Of course. 🙈

2022-07-26 08:34 UTC, nickvergessen approved these changes

2022-07-26 08:34 UTC, nickvergessen requested changes

2022-07-26 08:34 UTC, nickvergessen commented on src/components/AppContent/AppDetailsToggle.vue
> +	<Button v-tooltip="title" class="app-details-toggle">
missing aria-label or string content

2022-07-27 07:37 UTC, nickvergessen approved these changes
LGTM but couldn't find how to test this.

2022-07-27 14:24 UTC, marcoambrosini approved these changes

2022-07-27 14:24 UTC, merged