Add NoteCard component
nextcloud/nextcloud-vue pull request #2910
Opened 2022-08-02 14:49 UTC by CarlSchwan

![image](https://user-images.githubusercontent.com/23653902/182403884-e78787ea-9034-4bf7-b52b-92e68329d4cb.png)

Already used in the login pages and in a few settings

2022-08-02 14:55 UTC, jancborchardt requested changes
Nice! :) Details:
- [ ] I’d probably cut this border, then it looks cleaner? Also would then look more like the callout boxes in Text
- [ ] Similar with the box-shadow – we don’t really use shadow a lot, and it doesn’t make a lot of sense for this container (we don’t use it for the Text callout boxes either)
- [ ] Is the text color accessible / readable on all the possible backgrounds? 0.2 opacity is used, whereas for color-primary-light we use 10%, so we should probably adjust the values here to 0.1 as well so it’s a bit less intense?

2022-08-02 14:57 UTC, jancborchardt commented
Oh and also, this seems like it can be aligned with the notification component? Basically same thing: Container and bar on the left, just one is placed in the content, one on the top right with an x button (and possibly other actions like "undo").

2022-08-04 09:43 UTC, CarlSchwan commented
> Nice! :) Details:
> 
>     * [ ]  I’d probably cut this border, then it looks cleaner? Also would then look more like the callout boxes in Text
> 
>     * [ ]  Similar with the box-shadow – we don’t really use shadow a lot, and it doesn’t make a lot of sense for this container (we don’t use it for the Text callout boxes either)
> 
>     * [ ]  Is the text color accessible / readable on all the possible backgrounds? 0.2 opacity is used, whereas for color-primary-light we use 10%, so we should probably adjust the values here to 0.1 as well so it’s a bit less intense?

The text color is accessible with 0.20 and I got a contrast ratio of >11. But I experimented a bit with the various transparency level and I kinda like 15% more:

15%

![image](https://user-images.githubusercontent.com/23653902/182816740-08687028-cba0-4369-9c91-2bf38c21f5f7.png)

10%

2022-08-04 10:55 UTC, nickvergessen commented
Can you also make dark mode screenshots? Would like to see how that turns out.

2022-08-08 13:27 UTC, jancborchardt commented
Looks good @CarlSchwan! :) I’d go for 10% so it’s in line with our usage of the primary-light (as will the new design for tags and avatars), and also because it looks much nicer than the slightly darker background colors.

2022-08-09 13:51 UTC, vinicius73 commented
I guess we can make it closer with `text app callouts` in some way.

![callouts](https://user-images.githubusercontent.com/1561347/183666254-4c05ff39-336f-4ab8-aec8-04015b9db9e0.png)

2022-08-23 15:29 UTC, CarlSchwan commented
I updated the screenshot

2022-08-23 15:58 UTC, tcitworld commented on src/components/NcNoteCard/NcNoteCard.vue
> +	border-left: 4px solid var(--note-theme);
```suggestion
	border-inline-start: 4px solid var(--note-theme);
```
If you want to support rtl languages.

2022-08-24 12:48 UTC, jancborchardt approved these changes
Looks great! :) And now this we can also use for the login screen for the "Wrong account name or password" notice

2022-08-24 12:56 UTC, raimund-schluessler commented on src/components/NcNoteCard/NcNoteCard.vue
> +			default: () => 'warning',
Doesn't need to be a function
```suggestion
			default: 'warning',
```

2022-08-24 12:57 UTC, raimund-schluessler commented on src/components/NcNoteCard/NcNoteCard.vue
> +			default: () => false,
```suggestion
			default: false,
```

2022-08-24 12:58 UTC, raimund-schluessler commented on src/components/NcNoteCard/NcNoteCard.vue
> +			required: false,
```suggestion
			default: '',
```

2022-08-24 13:01 UTC, raimund-schluessler commented on src/components/NcNoteCard/NcNoteCard.vue
> +			validator: type => type === 'success' || type === 'warning' || type === 'error',
```suggestion
			validator: type => ['success', 'warning', 'error'].includes(type),
```

2022-08-24 13:07 UTC, raimund-schluessler approved these changes

2022-08-24 14:01 UTC, merged