Prevent tabbing into closed navigation
nextcloud/nextcloud-vue pull request #3114
Opened 2022-08-29 21:33 UTC by PVince81

When the navigation is closed, add "inert" attribute to prevent tabbing
into the sidebar.

- [ ] FIXME: `inert="false"` does NOT disable inert, need to remove the attribute completely :unamused:

2022-08-29 21:38 UTC, PVince81 commented
according to https://stackoverflow.com/a/64598898 just setting the attribute to null should make Vue remove it

2022-08-29 21:39 UTC, PVince81 commented
would be good to do some tests with an app that has the sidebar

sadly the style guide cannot test the app navigation

2022-08-29 21:40 UTC, PVince81 commented
does anyone has a working npm link setup to quickly test this ?

2022-08-29 22:34 UTC, vinicius73 approved these changes
The change seems ok, Vue will remove this prop.
But I did not test it properly.

Maybe a full example of this component will help in future changes.

2022-08-30 07:49 UTC, skjnldsv commented
Inert seems not supported enough yet :(
![image](https://user-images.githubusercontent.com/14975046/187380726-513a9d34-1d63-4987-95c6-d6c8fbb3ab82.png)

2022-08-30 08:07 UTC, nickvergessen approved these changes

2022-08-30 08:08 UTC, nickvergessen commented
> Inert seems not supported enough yet :(

Well sounds like we can fix most of the browsers now and the last one will catch up eventually.

2022-08-30 08:44 UTC, skjnldsv commented
> > Inert seems not supported enough yet :(
> 
> Well sounds like we can fix most of the browsers now and the last one will catch up eventually.

Not really, the browser versions are all very new. Chrome 102 is just from last May.
We should consider another approach too imho

2022-08-30 08:45 UTC, skjnldsv requested changes
See comments

2022-08-30 09:55 UTC, PVince81 commented
> We should consider another approach too imho

we could look into polyfills for inert

I don't think we should invest time trying to hack this around on our own, unless quick, easy and reliable

in caniuse it said Firefox 106 supports it now: https://caniuse.com/?search=inert

2022-08-30 10:32 UTC, skjnldsv commented
> in caniuse it said Firefox 106 supports it now: [caniuse.com/?search=inert](https://caniuse.com/?search=inert)

Scheduled to be released on 2022-10-18 :confused:

2022-08-30 10:35 UTC, skjnldsv commented
Also: 
![image](https://user-images.githubusercontent.com/14975046/187415622-79d900db-ff31-4b8f-9665-aa69a9bad04c.png)

2022-08-30 14:36 UTC, PVince81 commented
tabindex="-1" on the container doesn't fix sub-items as far as I remember.
we'd need to set this on every link and field within the sidebar and remember its original value, if any, and then reset it back
quite an involved hack

2022-08-30 14:39 UTC, PVince81 commented
idea: would it be possible to unmount the navigation when it's closed after a small delay ? then mount it again when opened ?

might cause delays though when mounting again while the user is swiping

2023-05-31 16:46 UTC, susnux commented
Currently 88% of global users are supported, the remaining missing browsers from our browserslist config are currently Safari 15.4 and Firefox ESR.

I think this approach:
> Well sounds like we can fix most of the browsers now and the last one will catch up eventually.

 is now good enough for version 8 / NC28 (meaning I think this is fine for current master).

2023-06-06 13:16 UTC, skjnldsv approved these changes

2023-06-06 13:16 UTC, merged

2023-08-25 08:19 UTC, raimund-schluessler commented
This seems to break opening the sidebar when it is closed, see https://github.com/nextcloud-libraries/nextcloud-vue/issues/4433

2023-08-25 11:02 UTC, susnux commented
I think we need to move the button outside the navigation element