Fix actions positioning
nextcloud/nextcloud-vue pull request #3157
Opened 2022-09-02 10:57 UTC by juliushaertl

- Limit height of the NcActions popover
- Fix placement of the NCAppNavigationItem actions menu

2022-09-02 11:00 UTC, raimund-schluessler commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +					:boundaries-element="'#content-vue'"
```suggestion
					boundaries-element="#content-vue"
```

2022-09-02 12:05 UTC, ChristophWurst approved these changes

2022-09-02 13:23 UTC, raimund-schluessler commented
Will this solve #3146?

2022-09-02 15:29 UTC, raimund-schluessler commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +			default: 'auto',
Can we keep this at `bottom`? It works the equally well and does not change the old behaviour. Or was there a specific reason / design decision for this change?
```suggestion
			default: 'bottom',
```

2022-09-02 16:54 UTC, raimund-schluessler commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +					boundaries-element="#content-vue"
If we set the container to `#app-navigation-vue`, the hidden overflow issue in #3146 is fixed as well, but additionally, the Actions menu is not jumping/moving when the body is scrolled.
```suggestion
					container="#app-navigation-vue"
					boundaries-element="#content-vue"
```

2022-09-02 16:55 UTC, raimund-schluessler requested changes
I can confirm that this fixes #3146.
However, I would propose to set the `container` properly, see https://github.com/nextcloud/nextcloud-vue/pull/3157/files#r961861481

2022-09-02 17:20 UTC, raimund-schluessler commented
/backport to stable6

2022-09-05 10:43 UTC, GretaD commented
@raimund-schluessler Julius is on holiday, do you want to take over and deliver the(your) comments :P. I can also rebase and change the stuff as you proposed

2022-09-05 11:14 UTC, raimund-schluessler commented
> @raimund-schluessler Julius is on holiday, do you want to take over and deliver the(your) comments :P. I can also rebase and change the stuff as you proposed

Sure, I can do that. I just didn't want to force my changes, as there might be specific reasons for the changes. But I guess we can still adjust it before a stable 6.0.0. release if necessary.

2022-09-05 11:22 UTC, raimund-schluessler approved these changes

2022-09-05 11:26 UTC, merged