v7.5.0
nextcloud/nextcloud-vue pull request #3663
Opened 2023-01-18 00:47 UTC by Pytal

2023-01-18 07:56 UTC, skjnldsv commented
Please put the changelog in the first post

2023-01-19 07:37 UTC, raimund-schluessler commented
Can we rebase so we get #3665 in as well?

2023-01-19 08:32 UTC, PVince81 commented
@raimund-schluessler if urgent, can you do this yourself and update the changelog commit + top post ?

2023-01-19 08:34 UTC, skjnldsv commented
It should not be in the changelog as it's documentation.
Changelog = library related changes only :)

2023-01-19 08:36 UTC, skjnldsv commented
Btw there is a mistake in the changelog, it seems I opened a duplicate PR with 
- https://github.com/nextcloud/nextcloud-vue/pull/3654
- https://github.com/nextcloud/nextcloud-vue/pull/3653

https://github.com/nextcloud/nextcloud-vue/pull/3654 got reviewed and merged, so github assumed https://github.com/nextcloud/nextcloud-vue/pull/3653 was too since the commit was the same.
We can remove https://github.com/nextcloud/nextcloud-vue/pull/3653 from the changelog :)

2023-01-19 08:36 UTC, skjnldsv requested changes

2023-01-19 08:36 UTC, skjnldsv commented on CHANGELOG.md
> +- Breadcrumb: add exact prop and fix style [\#3653](https://github.com/nextcloud/nextcloud-vue/pull/3653) ([skjnldsv](https://github.com/skjnldsv))
```suggestion
- Breadcrumb: add exact prop and fix style [\#3654](https://github.com/nextcloud/nextcloud-vue/pull/3654) ([skjnldsv](https://github.com/skjnldsv))
```

2023-01-19 08:39 UTC, raimund-schluessler commented
> It should not be in the changelog as it's documentation.
> 
> Changelog = library related changes only :)

Nevermind, I thought it's a bugfix. If it's only documentation, it doesn't need to be in the release.

2023-01-19 22:19 UTC, raimund-schluessler approved these changes

2023-01-20 00:53 UTC, merged

2023-01-20 01:05 UTC, Pytal commented
Able to release as admin @skjnldsv? https://github.com/nextcloud/nextcloud-vue/actions/runs/3963753999

2023-01-23 18:05 UTC, Pytal commented
👆 Please ignore @skjnldsv :) Already done by @AndyScherzinger :)