Use NcSelect for timezone picker
nextcloud/nextcloud-vue pull request #3781
Opened 2023-02-17 21:31 UTC by raimund-schluessler

This PR moves `NcTimezonePicker` from using `NcMultiselect` to `NcSelect`. Since `NcSelect` does not support grouping, I had to work around this a bit, but the outcome is the same as when using `NcMultiselect`. I additionally enhanced the search function a bit, so one can now also search for the continent name and see all timezones e.g. in Europe and searching for "Europe London", will give the correct timezone.

The styling probably needs a bit of adjustment still, because it currently uses the default `NcSelect` style with a gray/blue border, whereas the current timezone picker has no border. But maybe we want to update the style here and match with the other pickers, so I left it for now.

Before:
![image](https://user-images.githubusercontent.com/2496460/219797388-f8e84b5f-21b9-4051-aa06-2275c9251f46.png)

After:
![image](https://user-images.githubusercontent.com/2496460/219797486-75737bbb-f74a-4a96-b843-421c37fbf251.png)

2023-02-20 13:33 UTC, jancborchardt requested changes
Very cool! :) I think the blue border around it is actually nice. 

3 things:
- [ ] Style-wise it coukd look a bit more like the ActionMenu component, with the entries not expanding the whole width, but having a bit of margin and having a birder-radius
- [ ] The contrast of the highlight seems to not be enough for accessibility, here we should also do it however we make the ActionMenu entry hover/focus accessible cc @JuliaKirschenheuter @Pytal
- [ ] Detail: The height of the co tainer should (if possible) always cut the list at ½ of the last entry, so that one entry is cut off and it is obvious to people that the list continues. :)

2023-02-20 13:59 UTC, jancborchardt approved these changes
Sounds good, thanks for opening the issue, approved design-wise then. :)

2023-02-21 19:32 UTC, susnux approved these changes

2023-02-21 19:54 UTC, raimund-schluessler commented
I adjusted the search code a bit, so that the continent labels are shown if one region matches, just like with the old picker.

2023-02-21 20:10 UTC, merged