Display related resources error in note card
nextcloud/nextcloud-vue pull request #3852
Opened 2023-03-03 20:14 UTC by Pytal

| | Screenshot |
--- | ---
**Before (Top-right toast + empty panel area)** | ![image](https://user-images.githubusercontent.com/24800714/222816642-6529c237-c268-4a36-b237-751a492297b9.png) ![image](https://user-images.githubusercontent.com/24800714/222816603-5dd80c88-2ca0-42b2-b237-b94a90c02826.png)
**After** | ![image](https://user-images.githubusercontent.com/24800714/222816613-8ee1018a-fb58-4eb6-804a-4b49fa62d7d8.png)

2023-03-03 20:17 UTC, Pytal commented
/l10n-update

2023-03-04 10:56 UTC, raimund-schluessler commented on src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
> +			descriptionTranslated: this.t('Anything shared with the same group of people will show up here'),
This breaks the l10n extraction. See above, the strings got removed.

2023-03-04 10:57 UTC, raimund-schluessler commented on src/components/NcRelatedResourcesPanel/NcResource.vue
> +			labelTranslated: this.t('Open link to "{resourceTitle}"', { resourceTitle: this.title }),
Please keep it as it is, the l10n extraction does not work for the mixin.

2023-03-04 10:57 UTC, raimund-schluessler requested changes
Please see the l10n problems.

2023-03-06 10:22 UTC, artonge approved these changes

2023-03-15 22:05 UTC, Pytal commented
@nimishavijay @jancborchardt any additional design suggestions?

2023-03-15 22:37 UTC, nimishavijay commented
Looks good to me! ccing @jancborchardt to double check the wording :)

2023-03-16 16:22 UTC, jancborchardt approved these changes
Looks good to me as well! :)

2023-03-16 17:19 UTC, merged

2023-04-05 09:43 UTC, nickvergessen commented on src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
> +				return t('Error getting related resources. Please contact your system administrator if you have any questions.')
From my side of things this is not correct. When the 400 error occurs with Talks 1-1 chats there is nothing I as sysadmin was able to do about it.

2023-04-05 16:58 UTC, nickvergessen commented on src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
> +				return t('Error getting related resources. Please contact your system administrator if you have any questions.')
Further details in the comments over there: https://github.com/nextcloud/spreed/pull/9256#issuecomment-1497089458

Now that logging is added it actually makes sense, but i find it weird that the error is not using the normal showError anymore