Replace unmaintained HammerJS dependency with VueUse
nextcloud/nextcloud-vue pull request #3894
Opened 2023-03-15 17:38 UTC by susnux

HammerJS is unmaintained, ref: https://github.com/hammerjs/hammer.js/issues/1278

Replaced with VueUse which will be quite useful as we can also use it for #3893 so we can replace two unmaintained dependencies with one maintained one.

(Not relevant but this also will fix issues when building nextcloud-vue with vite (maybe in the future)).

2023-03-16 10:47 UTC, Pytal approved these changes

2023-03-20 12:56 UTC, susnux commented on src/components/NcAppContent/NcAppContent.vue
> -		if (this.allowSwipeNavigation) {
:+1: fixed

2023-03-24 09:51 UTC, marcoambrosini reviewed
I'm trying to test this from the web in mobile mode but it doesn't work for the app navigation

2023-05-09 18:53 UTC, ShGKme requested changes
I tried in Talk, and swipe for the left sidebar doesn't work for me now....
Nextcloud 27, Android, Vivaldi (Chromium-based).

Does it work for you in any app/mobile browser?

2023-05-15 12:22 UTC, ShGKme approved these changes
Tested on Android - Vivaldi (Chromium) and Firefox - works fine.

@marcoambrosini Could you also test on iPhone Safari?

2023-05-15 12:46 UTC, marcoambrosini approved these changes
Tested and works on safari mobile

2023-05-16 20:16 UTC, raimund-schluessler approved these changes

2023-05-16 20:16 UTC, merged