fix toggle overlapping other stuff
nextcloud/nextcloud-vue pull request #4134
Opened 2023-05-17 11:55 UTC by szaimen

Fix https://github.com/nextcloud/nextcloud-vue/pull/4103#issuecomment-1551128985

2023-05-17 11:55 UTC, szaimen commented
/backport to stable7

2023-05-17 12:13 UTC, Jerome-Herbinet approved these changes
LGTM after a fast test :
[Capture vidéo du 17-05-2023 14:10:04.webm](https://github.com/nextcloud/nextcloud-vue/assets/33763786/5ba13ea7-d9f2-4e34-8265-3f0a846f0da2)

May some other reviewers test it ?

2023-05-17 13:07 UTC, GretaD commented
if this is the result we want, then works for me too
![Screenshot from 2023-05-17 15-07-28](https://github.com/nextcloud/nextcloud-vue/assets/12728974/2e94d4da-40b3-45f8-8b10-2820dc9f0c8f)

2023-05-17 13:08 UTC, GretaD approved these changes

2023-05-17 13:19 UTC, raimund-schluessler commented
> if this is the result we want, then works for me too ![Screenshot from 2023-05-17 15-07-28](https://user-images.githubusercontent.com/12728974/238959355-2e94d4da-40b3-45f8-8b10-2820dc9f0c8f.png)

I would tend to say that the collapse button should be on the very right:
![Screenshot 2023-05-17 at 15-18-59 Nextcloud Vue Style Guide](https://github.com/nextcloud/nextcloud-vue/assets/2496460/2b7c107d-7c10-4d7e-bf4b-2a68bd581fea)

Minor reordering of the elements would make this work.

2023-05-17 14:20 UTC, raimund-schluessler commented
> > Minor reordering of the elements would make this work.
> 
> Can you submit a patch? I am not sure where to adjust this...

I can try, but I don't have a dev environment at hand right now.

2023-05-17 14:51 UTC, szaimen commented
> > > Minor reordering of the elements would make this work.
> > 
> > 
> > Can you submit a patch? I am not sure where to adjust this...
> 
> Should work now. See the enhanced example in the docs. I didn't test it in an app though.

Thanks a lot! :)

2023-05-17 14:53 UTC, szaimen commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +			display: initial;
I think one of this changes now reverted the idea of https://github.com/nextcloud/nextcloud-vue/pull/4103...

2023-05-17 14:53 UTC, szaimen commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +			display: initial;
cc @Jerome-Herbinet

2023-05-17 15:02 UTC, szaimen commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +			display: initial;
Really? Interesting!

2023-05-17 15:03 UTC, szaimen commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +			display: initial;
I see

2023-05-17 21:55 UTC, jancborchardt requested changes
Like noted in the other PRs: It would be good if the arrow is pointing down also in closed state.
It pointing to the right is unexpected – pointing down in both states would make it look like a standard HTML select element.

2023-05-19 16:48 UTC, raimund-schluessler commented
> Like noted in the other PRs: It would be good if the arrow is pointing down also in closed state. It pointing to the right is unexpected – pointing down in both states would make it look like a standard HTML select element.

I wouldn't say it's entirely unexpected. Even Google still uses this pattern in their apps sometimes (e.g. Googlemail Web). But they indeed seem to switch to an up/down arrow for open/closed state, e.g. in their expandable list view:
https://m3.material.io/components/lists/guidelines#f6fe9c4e-7498-420a-b820-d12a2b59fc99
<img width="676" alt="unnamed" src="https://github.com/nextcloud/nextcloud-vue/assets/2496460/46cb7f4a-b25c-4699-bd21-1edf16223f74">

So, how about we do this as well? Menu collapsed: arrow down, Menu open: arrow up?

2023-05-19 17:00 UTC, raimund-schluessler commented
> So, how about we do this as well? Menu collapsed: arrow down, Menu open: arrow up?

I implemented it like this. Please have a look.

2023-05-23 11:20 UTC, jancborchardt approved these changes
Yep, looks good now!

2023-05-23 11:26 UTC, raimund-schluessler commented
> The dropdown icon when collapsed is not shown permanently:
> without hover 	with hover
> ![image](https://user-images.githubusercontent.com/42591237/240251861-2940411a-2d7c-4170-8919-01514d3f7faf.png) 	![image](https://user-images.githubusercontent.com/42591237/240251692-8c154f3d-a60a-4457-b625-d6879d1cf60f.png)
> 
> cc @Jerome-Herbinet

How about we simply show it all the time (when collapsed and open). I would find it confusing to only show it when collapsed and hide it when open.

2023-05-23 13:40 UTC, merged

2023-05-23 17:28 UTC, szaimen commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +		display: none;
@raimund-schluessler can the above be addressed by simply setting this to display:initial?